on: [push]
permissions:
  contents: write
name: Lint, test and publish
jobs:
  lint-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: make venv lint test
      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          if git diff --name-only HEAD~1..HEAD | grep VERSION ; then
            echo "VERSION has changed, publishing a new version"
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases \
                -d "{\"tag_name\":\"$(cat VERSION)\",\"generate_release_notes\":true}"
          else
            echo "VERSION has not changed"
          fi
